### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by yu275184637** [liop/AlipaySDK#1]
请问你是如何pod spec lint alipaySdk.podspec 通过的？我现在用15.5.5版本的支付宝SDK报以下错误：

/Users/yz/Library/Developer/Xcode/DerivedData/App-gaetliwqjaokdkbqatwtuowmikul/Build/Products/Release-iphonesimulator/App.app/App
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_UTDevice", referenced from:
          objc-class-ref in AlipaySDK
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Ld /Users/yz/Library/Developer/Xcode/DerivedData/App-gaetliwqjaokdkbqatwtuowmikul/Build/Products/Release-iphonesimulator/App.app/App normal x86_64
    (1 failure)
   Testing with `xcodebuild`. 
 -> alipaySdk (15.5.5)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command/spec/lint.rb:87:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by liop** [comment]
你需要贴上你的podspec文件，我才能知道问题在哪。
或者你该搜索下 "OBJC_CLASS$_UTDevice", 很多类似问题的文章。

**Comment by yu275184637** [comment]
您好，以下是我的podspec文件：
Pod::Spec.new do |s|

  s.name         = "AlipaySDK_iOS"
  s.version      = "15.5.5"
  s.summary      = "支付宝官方SDK(15.5.5)"
  s.description  = <<-DESC
                    支付宝官方SDK
                   DESC

  s.homepage     = "https://docs.open.alipay.com/204/105295/"
  s.license      = "MIT"
  s.author       = { "yuze" => "yu275184637@163.com" }
  s.platform     = :ios, "9.0"
  s.source       = { :git => "https://git.coding.net/xiamidoushi/AlipaySDK_iOS.git", :tag => s.version }
  s.resource     = "AlipaySDK/AlipaySDK.bundle"
  s.vendored_frameworks = "AlipaySDK/AlipaySDK.framework"
  s.frameworks = "SystemConfiguration", "CoreTelephony", "QuartzCore", "CoreText", "CoreGraphics", "UIKit", "Foundation", "CFNetwork", "CoreMotion"
  s.libraries = "c++","z"
  s.requires_arc = true
end

执行的init命令是： pod spec lint AlipaySDK.podspec --allow-warnings --use-libraries --verbose

**Comment by liop** [comment]
[看这篇文章](https://blog.csdn.net/wm9028/article/details/51539841)

sdk需要用demo中的文件

![image](https://user-images.githubusercontent.com/5468141/45193475-bfe7d600-b280-11e8-8e86-3ce5e0473714.png)

**Comment by yu275184637** [comment]
好的，多谢指点 😆
